### ISSUE TITLE
Amigos dos Animais

### ISSUE THREAD

**Issue by senegalha** [SouJunior-Labs/atomics#10]
**Descrição enviada pelo formulário de registro de projeto**:
"Olá,

O objetivo deste projeto é criar um sistema web que servirá como um prontuário para animais de rua da cidade de São Domingos do Prata, cidade onde vivo e participo da comissão do projeto Amigos dos Animais. O sistema terá as seguintes funcionalidades inicialmente, podendo sofrer alterações de evolução da aplicação ao longo do tempo:

Cadastro de animais: O sistema permitirá que os voluntários da ONG cadastrem os animais que recebem ou resgatam. Os dados a serem cadastrados serão:

Nome do animal
Espécie
Raça
Sexo
Porte
Cor
Data de nascimento
Data de castração
Status (castrado/não castrado)
Localização

Atualmente estamos utilizando para organizarmos as informações antes que a aplicação esteja acessível.

Essa funcionalidade será importante para que a ONG tenha um controle dos animais que estão sob sua responsabilidade.

Gerenciamento de castração: O sistema permitirá que os voluntários da ONG acompanhem o status de castração dos animais. Eles poderão visualizar quais animais já foram castrados e quais ainda precisam ser castrados.
Essa funcionalidade será importante para que a ONG possa organizar e otimizar o processo de castração dos animais.

Busca de animais: O sistema permitirá que os interessados em adotar um animal possam realizar uma busca por raça, espécie, porte, cor, etc.
Essa funcionalidade será importante para facilitar o processo de adoção de animais.

O sistema será desenvolvido em uma plataforma web e estará disponível para acesso a partir de qualquer dispositivo com conexão à internet.

O projeto terá as seguintes etapas:

Requisitos: Nesta etapa, será definido o escopo do projeto e os requisitos funcionais e não funcionais do sistema.
Desenvolvimento: Nesta etapa, o sistema será desenvolvido de acordo com os requisitos definidos na etapa anterior.
Testes: Nesta etapa, o sistema será testado para garantir que atende aos requisitos funcionais e não funcionais definidos.
Implementação: Nesta etapa, o sistema será implantado em um ambiente de produção.
O projeto terá um prazo de conclusão de seis meses.

O orçamento do projeto é de R$ 0,00.

Acreditamos que este sistema será uma ferramenta valiosa para o projeto/ONG, pois facilitará o controle dos animais, o processo de castração e a adoção de animais.

Estamos à disposição para esclarecer quaisquer dúvidas que vocês possam ter.

Atenciosamente,

Frederico Espeschit

"

**Founder**:
Usuário Discord: fredericoespeschit#1963

**A fazer**

_Abordagem inicial_:
- [x] Conceder o cargo "⚒┃Temporary Founder" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [x] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [x] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [x] Aguardar, em inércia, até que o Founder tenha recrutado os membros do projeto e enviado o Pull Request;

_Após o Pull Request ter sido enviado pelo Founder_:
- [x] Revisar o Pull Request quando enviado, checando se está em conformidade com o que pedimos na Wiki;
- [x] Criar o cargo do projeto;
- [x] Na tela de cargos, nas configurações do SouJunior Labs no Discord, configurar as permissões dos cargos conforme os demais cargos de outros projetos;
- [x] Criar o post de Weekly do projeto;
- [x] Se e somente se o Founder tiver solicitado um espaço de chat no servidor, crie um canal para comunicação do time do projeto, também ajustando as permissões, porém deixe claro para o Founder que isso é opcional e que pode ser usado outro servidor no Discord, Microsoft Teams, Slack, Telegram, WhatsApp, etc, para comunicação.

**Comment by djhonantanparreira** [comment]
Tarefa finalizada.
