### ISSUE TITLE
Aluguemos

### ISSUE THREAD

**Issue by senegalha** [SouJunior-Labs/atomics#11]
**Descrição enviada pelo formulário de registro de projeto**:
"Aplicação em que usuários com objetos para alugar possam oferecê-los, indicando tempo mínimo e/ou máximo de aluguel, preço, etc. E usuários que desejam alugar, possam fazer isso.

Resumidamente, é um marketplace de aluguel."

**Founder**:
Usuário Discord: Vitor Matias#7597

**A fazer**

_Abordagem inicial_:
- [x] Conceder o cargo "⚒┃Temporary Founder" ao Founder;
- [x] Abordar o Founder no privado e informar que já é possível recrutar membros para o seu projeto;
- [ ] Garantir que tenha lido e entendido todo o fluxo de criação de projetos na Wiki, entendendo a necessidade de todos os cargos;
- [ ] Sinalizar a importância de todos os membros do projeto terem disponibilidade semelhante;
- [x] Se colocar à disposição para dúvidas;
- [ ] Aguardar, em inércia, até que o Founder tenha recrutado os membros do projeto e enviado o Pull Request;

_Após o Pull Request ter sido enviado pelo Founder_:
- [ ] Revisar o Pull Request quando enviado, checando se está em conformidade com o que pedimos na Wiki;
- [ ] Criar o cargo do projeto;
- [ ] Na tela de cargos, nas configurações do SouJunior Labs no Discord, configurar as permissões dos cargos conforme os demais cargos de outros projetos;
- [ ] Criar o post de Weekly do projeto;
- [ ] Se e somente se o Founder tiver solicitado um espaço de chat no servidor, crie um canal para comunicação do time do projeto, também ajustando as permissões, porém deixe claro para o Founder que isso é opcional e que pode ser usado outro servidor no Discord, Microsoft Teams, Slack, Telegram, WhatsApp, etc, para comunicação.

**Comment by djhonantanparreira** [comment]
Não virou projeto, Founder concluiu fase de recrutamento e marcou reunião mas não compareceu. Galera se desmotivou, ele tentou voltar atrás mas não conseguiu e por falta de retorno da galera decidiu não seguir com o projeto.

Portanto, não virou projeto e tarefa considerada concluida.
