### ISSUE TITLE
liberar chat-geral

### ISSUE THREAD

**Issue by Soaressluiss** [SouJunior-Labs/atomics#15]
# Liberação chat-geral
O **chat-geral** do servidor SJL no discord é um canal de texto onde todos os membros do servidor possam conversar entre si, independente do projeto que eles fazem parte. Ele havia sido desativado pois os membros estavam usando o canal de forma inadequada, e isso estava atrapalhando o andamento dos projetos.
Devido ao fato de ninguém usar este canal para o propósito que foi criado, sendo usado muitas vezes para remover dúvidas, mesmo existindo o fórum ⁠[❓┃dúvidas-e-sugestões](https://discord.com/channels/759176734460346423/1019681853017440316), o Dan decidiu pausar este canal por tempo indefinido.
No entanto, decidimos fazer a *liberação* do **chat-geral** novamente, mas com algumas regras para que o canal não seja usado de forma inadequada novamente.

**Comment by Soaressluiss** [comment]
@djhonantanparreira  Estava pensando em deletar aquele canal antigo e começar outro do zero (com o mesmo NOME), para dá a entender que é outra ideia com uma nova visão da forma como aquele chat pode ser usado.

Podemos ir nas configs do servidor e deixar ele como padrão igual o anterior;

**Comment by djhonantanparreira** [comment]
> @djhonantanparreira Estava pensando em deletar aquele canal antigo e começar outro do zero (com o mesmo NOME), para dá a entender que é outra ideia com uma nova visão da forma como aquele chat pode ser usado.
> 
> Podemos ir nas configs do servidor e deixar ele como padrão igual o anterior;

Show @Soaressluiss, podemos optar por fazer isso. Acredito que, seria interessante que quando criassemos o novo canal, deixassemos uma mensagem fixada dando um norte da nova proposta. 
Vou deixar aqui um exemplo, ainda preciso ter um brainstorming sobre a ideia.

---

Olá, pessoal! Tudo bem?

Estamos liberando o chat-geral novamente, no intuito de melhorar a comunicação entre os membros do servidor. No entanto, para que o canal não seja usado de forma inadequada novamente, decidimos que o canal será liberado com algumas regras.

Por exemplo, em caso de dúvidas específicas do assunto tal... ou em caso daquilo outro... ou em caso de tal coisa..

A ideia é que o chat-geral seja usado para conversas mais informais, e não para remover dúvidas ou conversas de áreas específicas.

**Comment by Soaressluiss** [comment]
Acho viável deixar fixada!

Sim, refinaremos essa mensagem;

**Comment by djhonantanparreira** [comment]
> Acho viável deixar fixada!
> 
> Sim, refinaremos essa mensagem;

Caso tenha alguma ideia ou sugestão, peço que fique a vontade pra compartilhar 🤓

**Comment by Soaressluiss** [comment]
@everyone

Estamos liberando o chat-geral novamente visando melhorar a comunicação entre os membros do servidor. Refletimos sobre as diretrizes anteriores e decidimos ser mais flexíveis em relação ao seu uso. No entanto, para evitar o uso inadequado do canal, estabelecemos algumas regras.

- Não toleramos qualquer forma de discriminação, seja com base em raça, gênero, religião, etc.
- Evite discussões que possam perturbar a paz do grupo, especialmente sobre temas sensíveis como religião e política.
- Abstenha-se de usar palavras ofensivas e termos pejorativos. Nosso bot possui filtro para esse tipo de vocabulário.
- Imagens, gifs e conteúdos graficamente chocantes não são permitidos.
- Não serão toleradas mensagens que violem a privacidade ou direitos autorais.
- Mantenha o respeito mútuo e evite comportamentos provocativos ou ofensivos.
- Não compartilhe informações pessoais ou sensíveis no chat-geral.
- É proibido o envio de spam ou mensagens repetitivas.

Em caso de dúvidas específicas, recomendamos que primeiro consultem o [Fórum de Dúvidas ou Sugestões]() para verificar se a questão já foi abordada.

A ideia é que o chat-geral seja utilizado para conversas informais e não para resolver dúvidas ou discussões de áreas específicas. Agradeço a cooperação de todos para mantermos um ambiente saudável e acolhedor.





@djhonantanparreira se quiser refinar mais, adicionar outras regras.

**Comment by Soaressluiss** [comment]
Estava pensando aqui faria sentido ter dois chats (um geral e outro para devs)?

Um para bate papo em geral e outro onde o pessoal de desenvolvimento, seja ele front, back, moblle e etc possam conversar sobre algo mais técnico, mandar código, tirar uma dúvida sobre uma tecnologia?

**Comment by djhonantanparreira** [comment]
> Estava pensando aqui faria sentido ter dois chats (um geral e outro para devs)?
> 
> Um para bate papo em geral e outro onde o pessoal de desenvolvimento, seja ele front, back, moblle e etc possam conversar sobre algo mais técnico, mandar código, tirar uma dúvida sobre uma tecnologia?

A proposta de criar um chat separado para desenvolvedores é interessante, pois pode facilitar a discussão de assuntos técnicos. No entanto, é importante considerar que isso pode dividir a comunidade e dificultar a comunicação entre os membros de diferentes áreas. 
Talvez se tivessemos uma abordagem parecida com a do chat-geral, onde limitaria esses chats apenas para dúvidas técnicas referentes à área. Porque deixar para a galera utilizar com um chat-geral de determinada área poderia se tornar uma problemática. 

---

Quanto a mensagem de liberação do chat-geral. Acredito que a sua já aborda tudo que deveria ser abordado, não tenho alterações em mente não. Acredito que podemos seguir com a liberação.

**Comment by Soaressluiss** [comment]
Poderíamos fazer dessa forma: 

Chat-geral (conversas diversas no servidor);
fórum dúvidas e sugestões (para coisas referentes a comunidade) aqui, por exemplo, (https://discord.com/channels/759176734460346423/1179542637787754556) era uma dúvida de back-end (Igor até me procurou no privado para saber como procederia);
Fórum para dúvidas técnicas, semelhante ao Fórum de "Dúvidas e sugestões", para responder perguntas desse tipo;

podem rever essa abordagem que sugerir;



OK, sobre a liberação do chat-geral 🤝🏻

Um adendo: fixa essa mensagem que refinamos e se possivel postar tambem no Guia do Servidor > servidor 


![Image](https://github.com/SouJunior-Labs/atomics/assets/98182255/71f7656d-bf28-4335-b2fe-531ea17f13ad)

**Comment by Soaressluiss** [comment]
Debate sobre o chat developer transferido para #2
