### ISSUE TITLE
Fórum  Dúvidas Techs

### ISSUE THREAD

**Issue by senegalha** [SouJunior-Labs/atomics#2]
**Descrição**:
Criação de um fórum específico para os membros sanarem suas dúvidas sobre tecnologias.

**Motivação**:
Espaço organizado para remoção de dúvidas tech, retirando esse trabalho do fórum de "dúvidas e sugestões" que está sendo usado de forma equivocada.

**O que deve ser feito nessa task:**
- [x] Criar o fórum *dúvidas Techs dentro da categoria "╭‒‒‒⥽ COMMUNITY " (no lugar de * usar o ícone referente algo  de tecnologia ou programação);
- [x] Não permitir que novos posts sejam criados por membros que não estejam na Staff;

**para o post de exemplo**
- [x] O post deve ter o nome "Dúvidas em <NOME_TECNOLOGIA_OU_FERRAMENTA>"
- [x] O post deve conter a mensagem em negrito: "Use este espaço para postar suas dúvidas em <NOME_TECNOLOGIA>;

**Ao final de tudo pronto**
- [x] criar uma mensagem para avisar a todos sobre o novo forum no canal "servidor"
- [x] atualizar a wiki, adicionando esse novo Fórum.

**Comment by djhonantanparreira** [comment]
@Soaressluiss vamos continuar nosso debate sobre a criação de uma área especifica para dúvidas relacionadas as tecnologias nessa issue. @oliverigor27 conto com sua contribuição também.

**Comment by Soaressluiss** [comment]
Ótimo! Podemos refinar essa ideia e liberar quanto antes para a comunidade. Segunda-feira na reunião podemos foca nesse ponto.

@oliverigor27 tem liberdade para participar dessa reunião e trazer alguns questionamentos e ideias.

**Comment by oliverigor27** [comment]
Tranquilo. Estarei presente na reunião segunda

**Comment by Soaressluiss** [comment]
## Mensagem de notificação para os membros no canal "Servidor".

Olá, @everyone 

Espero que estejam todos bem! Gostaria de compartilhar uma pequena atualização importante em relação aos nossos canais para tornar a experiência de todos ainda melhor.

Percebemos que o canal de #duvidasESugestoes estava sendo usado para tirar dúvidas específicas relacionadas a tecnologias, o que é fantástico! No entanto, para garantir que todos possam aproveitar ao máximo, decidimos criar um espaço dedicado para isso. Então, com entusiasmo, apresentamos o novo canal "Dúvidas Techs"!

A partir de agora, reservem o canal principal para perguntas relacionadas ao servidor em geral, sugestões e discussões abertas. Para todas as dúvidas sobre tecnologias, tópicos relacionados e afins, o canal "#Dúvidas-Techs" está à disposição para receber suas perguntas e contribuições brilhantes.

Agradecemos muito a compreensão de todos nessa mudança. Estamos sempre buscando maneiras de melhorar e adaptar o servidor para atender às suas necessidades. Se tiverem mais sugestões ou feedback, sintam-se à vontade para compartilhar!

**Comment by Soaressluiss** [comment]
Conferir na Wiki, ela não possui uma explicação sobre o fórum de "dúvidas e sugestões" acredito que seguindo a mesma lógica, não vejo necessidade de ter uma explicação sobre o fórum de "dúvidas techs", pois já seja algo subentendido e só a mensagem no canal de "servidor" já seja suficiente.

@djhonantanparreira avalie a mensagem que crie, depois valide-a.

**Comment by djhonantanparreira** [comment]
@Soaressluiss quanto a Wiki, creio que não precisamos modifica-la por enquanto. Segue sugestão de alteração do texto:

---

Olá, @everyone!

Espero que estejam bem! Temos uma novidade que vai deixar nossa comunidade ainda mais organizada e eficiente.

Observamos que o canal #❓┃dúvidas-e-sugestões  tem sido utilizado para dúvidas técnicas, o que é ótimo! Porém, para facilitar e otimizar ainda mais o suporte, criamos um espaço dedicado para isso: o canal #🤖┃dúvidas-tech!

A partir de agora, o canal principal #❓┃dúvidas-e-sugestões  será exclusivo para perguntas sobre o servidor em geral, sugestões e debates abertos. Todas as dúvidas relacionadas a tecnologias, ferramentas e assuntos similares devem ser direcionadas para o novo canal #🤖┃dúvidas-tech. Lá, estamos prontos para receber suas questões e contribuições valiosas.

Agradecemos a compreensão de todos nessa mudança. Continuamos buscando maneiras de melhorar e adaptar o servidor para atender às suas necessidades. Se tiverem mais sugestões ou feedback, fiquem à vontade para compartilhar!

Contamos com a participação de vocês para fazer do #🤖┃dúvidas-tech  um espaço rico em conhecimento e colaboração. Valorizamos imensamente suas sugestões e feedbacks, pois são essenciais para essa evolução contínua. Sintam-se à vontade para compartilhar suas ideias, apontar melhorias ou expressar suas opiniões.

Juntos, vamos tornar o ambiente ainda mais acolhedor e produtivo para todos!

**Comment by oliverigor27** [comment]
Nossa, esse canal vai ser ótimo!

**Comment by Soaressluiss** [comment]
Mensagem aprovada!
Finalizarei a moderação e até a noite liberarei o canal.

**Comment by djhonantanparreira** [comment]
Como foi feita a liberação do fórum #🤖┃dúvidas-tech no discord do Labs e a mensagem de anúncio já foi disparada, bem como todas as Tasks foram finalizadas, essa issue foi fechada.
