### ISSUE TITLE
Definição de frequência de publicações

### ISSUE THREAD

**Issue by senegalha** [SouJunior-Labs/atomics#8]
**Descrição**:
Definição do intervalo entre as publicações dos projetos nas mídias SouJunior Labs.

**Motivação**:
Trazer mais engajamento dos projetos e cumprir os benefícios previstos nas Stages.

**O que deve ser feito nessa task:**
- [ ] Análise da quantidade de projetos e do intervalo de publicações que traria mais engajamento.

**Comment by djhonantanparreira** [comment]
@Soaressluiss pensando nessa [mensagem](https://discordapp.com/channels/759176734460346423/1139987241150714077/1180990427554381886) que deixei lá no canal ```🌲┃founders-only```, gostaria de trazer a tona todas as issues que abordem esse assunto #7
